services:
  frontend:
    image: frontend
    build: .
    container_name: frontend
    ports:
      - 80:80
    networks:
      - mynetwork
    

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    networks:
      - mynetwork
    environment:
      - PGADMIN_DEFAULT_PASSWORD=16052021

networks:
  mynetwork:
    driver: bridge

volumes:
  myvolume:
